//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundFrame.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroundFrame.Core.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a path edge to this location node because the from location node is not saved to the GroundFrame.SQL Database.
        /// </summary>
        internal static string AddPathEdgeFromLocationNodeError {
            get {
                return ResourceManager.GetString("AddPathEdgeFromLocationNodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a path edge to this location node because the to location node is not saved to the GroundFrame.SQL Database.
        /// </summary>
        internal static string AddPathEdgeToLocationNodeError {
            get {
                return ResourceManager.GetString("AddPathEdgeToLocationNodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to GroundFrame Microsoft SQL Database.
        /// </summary>
        internal static string CannotConnectGFSQLDb {
            get {
                return ResourceManager.GetString("CannotConnectGFSQLDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location must be saved against the Simulation in the GroundFrame.SQL database before a Location Node can be created.
        /// </summary>
        internal static string CreateLocationNodeInvalidLocationError {
            get {
                return ResourceManager.GetString("CreateLocationNodeInvalidLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation Era must be saved against the Simulation in the GroundFrame.SQL database before a Location Node can be created.
        /// </summary>
        internal static string CreateLocationNodeInvalidSimEraError {
            get {
                return ResourceManager.GetString("CreateLocationNodeInvalidSimEraError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation must be saved to the GroundFrame.SQL database before a Location Node can be created.
        /// </summary>
        internal static string CreateLocationNodeUnsavedSimError {
            get {
                return ResourceManager.GetString("CreateLocationNodeUnsavedSimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation must be saved to the GroundFrame.SQL database before a Location can be created.
        /// </summary>
        internal static string CreateLocationUnsavedSimError {
            get {
                return ResourceManager.GetString("CreateLocationUnsavedSimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete a Location from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string DeleteLocationZeroIDError {
            get {
                return ResourceManager.GetString("DeleteLocationZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete a Simulation from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string DeleteSimulationZeroIDError {
            get {
                return ResourceManager.GetString("DeleteSimulationZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pass an Enum as the type parameter.
        /// </summary>
        internal static string EnumTypeException {
            get {
                return ResourceManager.GetString("EnumTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FileName cannot be found.
        /// </summary>
        internal static string FileNotFoundArgument {
            get {
                return ResourceManager.GetString("FileNotFoundArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string GeneralNullArgument {
            get {
                return ResourceManager.GetString("GeneralNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied index is out of range for the collection {0}.
        /// </summary>
        internal static string IndexOutOfRangeError {
            get {
                return ResourceManager.GetString("IndexOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataReader argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidDataReaderArgument {
            get {
                return ResourceManager.GetString("InvalidDataReaderArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Environment argument must be a valid environment.
        /// </summary>
        internal static string InvalidEnvironmentArgument {
            get {
                return ResourceManager.GetString("InvalidEnvironmentArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exception argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidExceptionArgument {
            get {
                return ResourceManager.GetString("InvalidExceptionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FileName argument cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string InvalidFileNameNullArgument {
            get {
                return ResourceManager.GetString("InvalidFileNameNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HalfMinuteCharacter cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string InvalidHalfMinuteCharacterArgument {
            get {
                return ResourceManager.GetString("InvalidHalfMinuteCharacterArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HalfMinuteCharacterASCII argument must be between 32 and 255.
        /// </summary>
        internal static string InvalidHalfMinuteCharacterASCIIArgument {
            get {
                return ResourceManager.GetString("InvalidHalfMinuteCharacterASCIIArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HalfMinuteCharacter argument must only be 1 character.
        /// </summary>
        internal static string InvalidHalfMinuteCharacterLengthArgument {
            get {
                return ResourceManager.GetString("InvalidHalfMinuteCharacterLengthArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied JSON is not in the correct format.
        /// </summary>
        internal static string InvalidJSONError {
            get {
                return ResourceManager.GetString("InvalidJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidLocationArgument {
            get {
                return ResourceManager.GetString("InvalidLocationArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location Node cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidLocationNodeArgument {
            get {
                return ResourceManager.GetString("InvalidLocationNodeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meters argument must be greater than zero.
        /// </summary>
        internal static string InvalidMeterArgument {
            get {
                return ResourceManager.GetString("InvalidMeterArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The speed must be greater than zero.
        /// </summary>
        internal static string InvalidMPHArgument {
            get {
                return ResourceManager.GetString("InvalidMPHArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name argument cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string InvalidNameArgument {
            get {
                return ResourceManager.GetString("InvalidNameArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name argument cannot be longer than {0} characters.
        /// </summary>
        internal static string InvalidNameLengthArgument {
            get {
                return ResourceManager.GetString("InvalidNameLengthArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Path Edge argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidPathEdgeArgument {
            get {
                return ResourceManager.GetString("InvalidPathEdgeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage argument must be between 0 and 100.
        /// </summary>
        internal static string InvalidPercentageArgument {
            get {
                return ResourceManager.GetString("InvalidPercentageArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seconds argument must be equal or greater than 0.
        /// </summary>
        internal static string InvalidSecondsArgument {
            get {
                return ResourceManager.GetString("InvalidSecondsArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation Era argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidSimEraArgument {
            get {
                return ResourceManager.GetString("InvalidSimEraArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SimSigCode argument cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string InvalidSimSigCodeArgument {
            get {
                return ResourceManager.GetString("InvalidSimSigCodeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code provided is not a valid SimSig code.
        /// </summary>
        internal static string InvalidSimSigCodeError {
            get {
                return ResourceManager.GetString("InvalidSimSigCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SimSig code argument cannot be longer than {0} characters.
        /// </summary>
        internal static string InvalidSimSigCodeLengthArgument {
            get {
                return ResourceManager.GetString("InvalidSimSigCodeLengthArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid or missing SimSig Electrification code has been supplied.
        /// </summary>
        internal static string InvalidSimSigElecCodeError {
            get {
                return ResourceManager.GetString("InvalidSimSigElecCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidSimulationArgument {
            get {
                return ResourceManager.GetString("InvalidSimulationArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation hasn&apos;t been saved to the GroundFrame.SQL database.
        /// </summary>
        internal static string InvalidSimulationNotSavedToDBArgument {
            get {
                return ResourceManager.GetString("InvalidSimulationNotSavedToDBArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQLConnector argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidSQLConnectorArgument {
            get {
                return ResourceManager.GetString("InvalidSQLConnectorArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Time Delimiter argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidTimeDelimiterArgument {
            get {
                return ResourceManager.GetString("InvalidTimeDelimiterArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Time Delimiter argument must be a single character.
        /// </summary>
        internal static string InvalidTimeDelimiterLengthArgument {
            get {
                return ResourceManager.GetString("InvalidTimeDelimiterLengthArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UserSettings argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidUserSettingsArgument {
            get {
                return ResourceManager.GetString("InvalidUserSettingsArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Version cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidVersionArgument {
            get {
                return ResourceManager.GetString("InvalidVersionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number cannot be less than zero.
        /// </summary>
        internal static string InvalidVersionNumberArgument {
            get {
                return ResourceManager.GetString("InvalidVersionNumberArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WTT Start Date cannot be before 01/01/1850.
        /// </summary>
        internal static string InvalidWTTStartDateArgument {
            get {
                return ResourceManager.GetString("InvalidWTTStartDateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidXMLArgument {
            get {
                return ResourceManager.GetString("InvalidXMLArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Environment argument cannot be &lt;NULL&gt; or an empty string.
        /// </summary>
        internal static string NullEnvironmentArgument {
            get {
                return ResourceManager.GetString("NullEnvironmentArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON string cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string NullOrEmptyJSONError {
            get {
                return ResourceManager.GetString("NullOrEmptyJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OnRequestUserSettings handler not assigned.
        /// </summary>
        internal static string OnRequestUserSettingsHandlerNotAssigned {
            get {
                return ResourceManager.GetString("OnRequestUserSettingsHandlerNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Caution Speed Set collection from the supplied XML.
        /// </summary>
        internal static string ParseFromXElementWTTCautionSpeedException {
            get {
                return ResourceManager.GetString("ParseFromXElementWTTCautionSpeedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Caution Speed Set collection from the supplied XML.
        /// </summary>
        internal static string ParseFromXElementWTTCautionSpeedSetException {
            get {
                return ResourceManager.GetString("ParseFromXElementWTTCautionSpeedSetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the WTT TimeTable from the Source SimSig WTT XML.
        /// </summary>
        internal static string ParseFromXElementWTTTimeTableException {
            get {
                return ResourceManager.GetString("ParseFromXElementWTTTimeTableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the WTT Train Category from the Source SimSig WTT XML.
        /// </summary>
        internal static string ParseFromXElementWTTTrainCategoryException {
            get {
                return ResourceManager.GetString("ParseFromXElementWTTTrainCategoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the WTT Trip from the Source SimSig WTT XML.
        /// </summary>
        internal static string ParseFromXElementWTTTripException {
            get {
                return ResourceManager.GetString("ParseFromXElementWTTTripException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to read the user settings from the supplied JSON string.
        /// </summary>
        internal static string ParseUserSettingsJSONError {
            get {
                return ResourceManager.GetString("ParseUserSettingsJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Activity collection from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTActivityCollectionJSONError {
            get {
                return ResourceManager.GetString("ParseWTTActivityCollectionJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Activity from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTActivityJSONError {
            get {
                return ResourceManager.GetString("ParseWTTActivityJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Caution Speed from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTCautionSpeedJSONError {
            get {
                return ResourceManager.GetString("ParseWTTCautionSpeedJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Caution Speed Set collection from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTCautionSpeedSetCollectionJSONError {
            get {
                return ResourceManager.GetString("ParseWTTCautionSpeedSetCollectionJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Caution Speed Set from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTCautionSpeedSetJSONError {
            get {
                return ResourceManager.GetString("ParseWTTCautionSpeedSetJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the WTT Header from the Source SimSig WTT XML.
        /// </summary>
        internal static string ParseWTTHeaderException {
            get {
                return ResourceManager.GetString("ParseWTTHeaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Timetable collection from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTTimeTableCollectionJSONError {
            get {
                return ResourceManager.GetString("ParseWTTTimeTableCollectionJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to read the Timetable from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTTimeTableJSONError {
            get {
                return ResourceManager.GetString("ParseWTTTimeTableJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Train Category collection from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTTrainCategoryCollectionJSONError {
            get {
                return ResourceManager.GetString("ParseWTTTrainCategoryCollectionJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to read the Train Category from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTTrainCategoryJSONError {
            get {
                return ResourceManager.GetString("ParseWTTTrainCategoryJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to parse the Trip collection from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTTripCollectionJSONError {
            get {
                return ResourceManager.GetString("ParseWTTTripCollectionJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to read the Trip from the supplied JSON string.
        /// </summary>
        internal static string ParseWTTTripJSONError {
            get {
                return ResourceManager.GetString("ParseWTTTripJSONError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error has occured trying to determine whether the Simulation {0} already exists in the GroundFrame.SQL database.
        /// </summary>
        internal static string QueuerCheckWTTExistsError {
            get {
                return ResourceManager.GetString("QueuerCheckWTTExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task has errored trying to save the simulation to the GroundFrame.SQL database.
        /// </summary>
        internal static string QueuerErrorSavingSimulation {
            get {
                return ResourceManager.GetString("QueuerErrorSavingSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to complete the task..
        /// </summary>
        internal static string QueuerGenericFailureMessage {
            get {
                return ResourceManager.GetString("QueuerGenericFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As error has occured trying to retrieve the template era for {0} from the GroundFrame.SQL databae.
        /// </summary>
        internal static string QueuerGetTemplateSimEraFromGroundFrameSQLDB {
            get {
                return ResourceManager.GetString("QueuerGetTemplateSimEraFromGroundFrameSQLDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured trying to retrieve version {0} from the GroundFrame.SQL database.
        /// </summary>
        internal static string QueuerGetVersionFromGroundFrameSQLDB {
            get {
                return ResourceManager.GetString("QueuerGetVersionFromGroundFrameSQLDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error has occured trying to read the WTT File {0}.
        /// </summary>
        internal static string QueuerLoadWTTFromFileError {
            get {
                return ResourceManager.GetString("QueuerLoadWTTFromFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot refresh a simulation from the GroundFrame.SQL database if it hasn&apos;t yet been saved to the GroundFrame.SQL database.
        /// </summary>
        internal static string RefreshSimulationError {
            get {
                return ResourceManager.GetString("RefreshSimulationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred trying to retrieve all Simulation records from the GroundFrame.SQL database.
        /// </summary>
        internal static string RetieveAllSimsError {
            get {
                return ResourceManager.GetString("RetieveAllSimsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred trying to build the Location Mapper from TimeTable {0}.
        /// </summary>
        internal static string RetrieveLocationMapperError {
            get {
                return ResourceManager.GetString("RetrieveLocationMapperError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred trying to build the Location Node Mapper from TimeTable {0}.
        /// </summary>
        internal static string RetrieveLocationNodeMapperError {
            get {
                return ResourceManager.GetString("RetrieveLocationNodeMapperError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete a Simulation from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string RetrieveLocationZeroIDError {
            get {
                return ResourceManager.GetString("RetrieveLocationZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot load a Simulation from the GroundFrame.SQL Database when the SimSig Code is &lt;NULL&gt; or an empty string..
        /// </summary>
        internal static string RetrieveSimulationNullSimSigCodeError {
            get {
                return ResourceManager.GetString("RetrieveSimulationNullSimSigCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot load a Simulation from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string RetrieveSimulationZeroIDError {
            get {
                return ResourceManager.GetString("RetrieveSimulationZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred trying to retrieve all User setting records from the GroundFrame.SQL database.
        /// </summary>
        internal static string RetrieveUserSettingsRecordsError {
            get {
                return ResourceManager.GetString("RetrieveUserSettingsRecordsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred trying to retrieve all Version records from the GroundFrame.SQL database..
        /// </summary>
        internal static string RetrieveVersionRecordsError {
            get {
                return ResourceManager.GetString("RetrieveVersionRecordsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot load a Version from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string RetrieveVersionZeroIDError {
            get {
                return ResourceManager.GetString("RetrieveVersionZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is figured to be part of a test therefore you cannot tear down the data.
        /// </summary>
        internal static string TearDownError {
            get {
                return ResourceManager.GetString("TearDownError", resourceCulture);
            }
        }
    }
}
