//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundFrame.Classes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroundFrame.Classes.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to GroundFrame Microsoft SQL Database.
        /// </summary>
        internal static string CannotConnectGFSQLDb {
            get {
                return ResourceManager.GetString("CannotConnectGFSQLDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation must be saved to the GroundFrame.SQL database before a Location can be created.
        /// </summary>
        internal static string CreateLocationUnsavedSimError {
            get {
                return ResourceManager.GetString("CreateLocationUnsavedSimError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete a Location from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string DeleteLocationZeroIDError {
            get {
                return ResourceManager.GetString("DeleteLocationZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete a Simulation from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string DeleteSimulationZeroIDError {
            get {
                return ResourceManager.GetString("DeleteSimulationZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pass an Enum as the type parameter.
        /// </summary>
        internal static string EnumTypeException {
            get {
                return ResourceManager.GetString("EnumTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FileName cannot be found.
        /// </summary>
        internal static string FileNotFoundArgument {
            get {
                return ResourceManager.GetString("FileNotFoundArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string GeneralNullArgument {
            get {
                return ResourceManager.GetString("GeneralNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataReader argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidDataReaderArgument {
            get {
                return ResourceManager.GetString("InvalidDataReaderArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FileName argument cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string InvalidFileNameNullArgument {
            get {
                return ResourceManager.GetString("InvalidFileNameNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HalfMinuteCharacter cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string InvalidHalfMinuteCharacterArgument {
            get {
                return ResourceManager.GetString("InvalidHalfMinuteCharacterArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HalfMinuteCharacterASCII argument must be between 32 and 255.
        /// </summary>
        internal static string InvalidHalfMinuteCharacterASCIIArgument {
            get {
                return ResourceManager.GetString("InvalidHalfMinuteCharacterASCIIArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HalfMinuteCharacter argument must only be 1 character.
        /// </summary>
        internal static string InvalidHalfMinuteCharacterLengthArgument {
            get {
                return ResourceManager.GetString("InvalidHalfMinuteCharacterLengthArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meters argument must be greater than zero.
        /// </summary>
        internal static string InvalidMeterArgument {
            get {
                return ResourceManager.GetString("InvalidMeterArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The speed must be greater than zero.
        /// </summary>
        internal static string InvalidMPHArgument {
            get {
                return ResourceManager.GetString("InvalidMPHArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name argument cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string InvalidNameArgument {
            get {
                return ResourceManager.GetString("InvalidNameArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name argument cannot be longer than {0} characters.
        /// </summary>
        internal static string InvalidNameLengthArgument {
            get {
                return ResourceManager.GetString("InvalidNameLengthArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage argument must be between 0 and 100.
        /// </summary>
        internal static string InvalidPercentageArgument {
            get {
                return ResourceManager.GetString("InvalidPercentageArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seconds argument must be equal or greater than 0.
        /// </summary>
        internal static string InvalidSecondsArgument {
            get {
                return ResourceManager.GetString("InvalidSecondsArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SimSigCode argument cannot be &lt;NULL&gt; or empty.
        /// </summary>
        internal static string InvalidSimSigCodeArgument {
            get {
                return ResourceManager.GetString("InvalidSimSigCodeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code provided is not a valid SimSig code.
        /// </summary>
        internal static string InvalidSimSigCodeError {
            get {
                return ResourceManager.GetString("InvalidSimSigCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SimSig code argument cannot be longer than {0} characters.
        /// </summary>
        internal static string InvalidSimSigCodeLengthArgument {
            get {
                return ResourceManager.GetString("InvalidSimSigCodeLengthArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidSimulationArgument {
            get {
                return ResourceManager.GetString("InvalidSimulationArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simulation hasn&apos;t been saved to the GroundFrame.SQL database.
        /// </summary>
        internal static string InvalidSimulationNotSavedToDBArgument {
            get {
                return ResourceManager.GetString("InvalidSimulationNotSavedToDBArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQLConnector argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidSQLConnectorArgument {
            get {
                return ResourceManager.GetString("InvalidSQLConnectorArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Time Delimiter argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidTimeDelimiterArgument {
            get {
                return ResourceManager.GetString("InvalidTimeDelimiterArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Time Delimiter argument must be a single character.
        /// </summary>
        internal static string InvalidTimeDelimiterLengthArgument {
            get {
                return ResourceManager.GetString("InvalidTimeDelimiterLengthArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML argument cannot be &lt;NULL&gt;.
        /// </summary>
        internal static string InvalidXMLArgument {
            get {
                return ResourceManager.GetString("InvalidXMLArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the WTT TimeTable from the Source SimSig WTT XML.
        /// </summary>
        internal static string ParseFromXElementWTTTimeTableException {
            get {
                return ResourceManager.GetString("ParseFromXElementWTTTimeTableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the WTT Train Category from the Source SimSig WTT XML.
        /// </summary>
        internal static string ParseFromXElementWTTTrainCategoryException {
            get {
                return ResourceManager.GetString("ParseFromXElementWTTTrainCategoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the WTT Trip from the Source SimSig WTT XML.
        /// </summary>
        internal static string ParseFromXElementWTTTripException {
            get {
                return ResourceManager.GetString("ParseFromXElementWTTTripException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the WTT Header from the Source SimSig WTT XML.
        /// </summary>
        internal static string ParseWTTHeaderException {
            get {
                return ResourceManager.GetString("ParseWTTHeaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot refresh a simulation from the GroundFrame.SQL database if it hasn&apos;t yet been saved to the GroundFrame.SQL database.
        /// </summary>
        internal static string RefreshSimulationError {
            get {
                return ResourceManager.GetString("RefreshSimulationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred trying to retrieve all Simulation records from the GroundFrame.SQL database.
        /// </summary>
        internal static string RetieveAllSimsError {
            get {
                return ResourceManager.GetString("RetieveAllSimsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete a Simulation from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string RetrieveLocationZeroIDError {
            get {
                return ResourceManager.GetString("RetrieveLocationZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot load a Simulation from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string RetrieveSimulationZeroIDError {
            get {
                return ResourceManager.GetString("RetrieveSimulationZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred trying to retrieve all Version records from the GroundFrame.SQL database..
        /// </summary>
        internal static string RetrieveVersionRecordsError {
            get {
                return ResourceManager.GetString("RetrieveVersionRecordsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot load a Version from the GroundFrame.SQL Database when the ID is zero.
        /// </summary>
        internal static string RetrieveVersionZeroIDError {
            get {
                return ResourceManager.GetString("RetrieveVersionZeroIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is figured to be part of a test therefore you cannot tear down the data.
        /// </summary>
        internal static string TearDownError {
            get {
                return ResourceManager.GetString("TearDownError", resourceCulture);
            }
        }
    }
}
